baseUrl: "https://venicebotcenter.org"
languageCode: "it-it"
theme: 'PaperMod'
defaultContentLanguage: "it"
disqusShortname: "venice-bot-center"
publishDir: "docs"
paginate: 5
googleAnalytics: "G-GP45MH9DVJ"
title: Venice Bot Center

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Venice Bot Center
  description: "Sito del gruppo github di sviluppo bot per la città di venezia Venezia"
  keywords: [Blog, Bot, Telegram, Venezia]
  author: ["Venice Bot Center"]
  # author: ["Me", "You"] # multiple authors
  images: ["blue.png"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowBreadCrumbs: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon.png"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"


  label:
    text: "Home"
    icon: "/blue.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Venice Bot Center"
    subtitle: "Bot per Venezia"
    imageUrl: "/blue.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: logo
    buttons:
      - name: Articoli
        url: /post/
      - name: MareaBot
        url: https://t.me/mareavenezia
      - name: PolliniBot
        url: https://t.me/pollini_veneziani


  # home-info mode
  homeInfoParams:
    Title: "Venice Bot Center 🦾🤖"
    Content: "Questo progetto è nato da un progetto personale di un informatico ed è realizzato grazie a Python e agli open data del comune di Venezia.
Attualmente supportiamo un bot per le segnalazioni delle Maree e dei Pollini per la città di Venezia"

  socialIcons:
    - name: github
      url: "https://github.com/Venice-Bot-Center"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tags
      name: Tag Articoli
      url: /tags/
      weight: 2000000000
    - identifier: MareaBot
      name: MareaBot
      url: https://t.me/mareavenezia
      weight: 30
    - identifier: PolliniBot
      name: PolliniBot
      url: https://t.me/pollini_veneziani
      weight: 40
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

